import { defineStore } from 'pinia'
import { reactive } from 'vue'

export const useArticlesStore = defineStore('articles', {
  state: () => ({
    articles: reactive([
      {
        "title": "5ème session de la Commission mixte sino-béninoise à Beijing : La Chine et le Bénin pour une relation plus consolidée et durable",
        "author": "",
        "published_date": "2023-07-06 11:45:00",
        "published_date_precision": "timezone unknown",
        "link": "https://www.gouv.bj/article/2293/5eme-session-commission-mixte-sino-beninoise-beijing-chine-benin-relation-plus-consolidee-durable/",
        "clean_url": "gouv.bj",
        "excerpt": "Aujourd'hui à 10:57|Comptes rendus|FinanceLe lundi 03 juillet 2023, s'est tenue, à Beijing, en marge de la 3ème édition de l'Exposition économique et commerciale de Changsha, la 5ème session de la…",
        "summary": "Aujourd'hui à 10:57\n|\nComptes rendus\n|\nFinance\nLe lundi 03 juillet 2023, s'est tenue, à Beijing, en marge de la 3ème édition de l'Exposition économique et commerciale de Changsha, la 5ème session de la Commission Mixte de Coopération sino-béninoise. La délégation béninoise aux travaux de ladite Commission a été conduite par le Ministre d'État, Ministre de l'Économie et des Finances en charge de la Coopération, Monsieur Romuald WADAGNI, et comprend entre autres, le Ministre des Affaires étrangères, Monsieur Olushégun ADJADI BAKARI, et le Ministre de l'Industrie et du Commerce, Madame Shadiya ASSOUMAN, ainsi que l'Ambassadeur du Bénin à Beijing, Monsieur Simon-Pierre ADOVELANDE.",
        "rights": "gouv.bj",
        "rank": 89217,
        "topic": "news",
        "country": "BJ",
        "language": "fr",
        "authors": "",
        "media": "https://www.gouv.bj/upload/thumbnails/banners//876920953785001688641263.jpg?v=001",
        "is_opinion": false,
        "twitter_account": null,
        "_score": 18.012642,
        "_id": "cf0ac4d3f590179f0ba2b3429693d228"
      },
      {
        "title": "Développement des infrastructures agricoles : L'AFD accorde près de 20 milliards de FCFA au Bénin",
        "author": "Adjehounou Gérophibère",
        "published_date": "2023-07-07 17:00:00",
        "published_date_precision": "timezone unknown",
        "link": "https://lanouvelletribune.info/2023/07/developpement-des-infrastructures-agricoles-lafd-accorde-pres-de-20-milliards-de-fcfa-au-benin",
        "clean_url": "lanouvelletribune.info",
        "excerpt": "Le ministre d'Etat chargé de l'Economie et des Finances, Romuald Wadagni, de retour de sa participation à la 5ème session de la Commission mixte sino-béninoise",
        "summary": "Le ministre d'Etat chargé de l'Economie et des Finances, Romuald Wadagni, de retour de sa participation à la 5ème session de la Commission mixte sino-béninoise à Beijing en Chine, a signé en France avec l'Agence française de développement (AFD) deux conventions de financement au profit du Projet d'appui au développement et aux investissements agricoles productifs au Bénin (Padiap). Le montant de ce projet s'élève à 29,3 millions d'euros soit 19,2 milliards de Fcfa. Il va permettre entre autres le développement significatif des infrastructures agricoles dans diverses filières notamment le maïs, le riz et le soja.",
        "rights": "lanouvelletribune.info",
        "rank": 124345,
        "topic": "news",
        "country": "BJ",
        "language": "fr",
        "authors": "Adjehounou Gérophibère",
        "media": "https://lanouvelletribune.info/wp-content/uploads/2023/03/wadagni-6.webp",
        "is_opinion": false,
        "twitter_account": "@lntribune",
        "_score": 16.11915,
        "_id": "43e946ee3418ab801e9b86598b4369f7"
      },
      {
        "title": "COMMUNIQUE DE PRESSE",
        "author": "Matin Libre",
        "published_date": "2023-07-06 04:21:42",
        "published_date_precision": "full",
        "link": "https://matinlibre.com/2023/07/06/communique-de-presse-38/",
        "clean_url": "matinlibre.com",
        "excerpt": "Nestor Coffi, nouveau Représentant Résident de la Banque mondiale pour le BéninAssurer la mise en œuvre efficace et souple du Cadre de partenariat entre la Banque mondiale et le Bénin afin d'obtenir…",
        "summary": "Get real time updates directly on you device, subscribe now.\n \n\n\n \nNestor Coffi, nouveau Représentant Résident de la Banque mondiale pour le Bénin\n\n\nAssurer la mise en œuvre efficace et souple du Cadre de partenariat entre la Banque mondiale et le Bénin afin d'obtenir des résultats qui impactent la qualité de vie des populations.\n \nCotonou, le 5 juillet 2023. Le nouveau Représentant Résident de la Banque mondiale pour le Bénin a pris fonction officiellement le 1er juillet 2023. Monsieur Nestor Coffi, remplace Monsieur Atou Seck dont le mandat a pris fin le 30 juin 2023.",
        "rights": "matinlibre.com",
        "rank": 869184,
        "topic": "news",
        "country": "BJ",
        "language": "fr",
        "authors": "Matin Libre",
        "media": "https://matinlibre.com/wp-content/uploads/2023/07/9-2.jpg",
        "is_opinion": false,
        "twitter_account": null,
        "_score": 16.11636,
        "_id": "95619c56e230bfe72c7b5c6cda6d6dcf"
      },
      {
        "title": "Arrêtés et déposés en prison:  Que deviennent-ils ? (Le temps de la Justice…)",
        "author": "Matin Libre",
        "published_date": "2023-07-06 04:19:18",
        "published_date_precision": "full",
        "link": "https://matinlibre.com/2023/07/06/arretes-et-deposes-en-prison-que-deviennent-ils-le-temps-de-la-justice/?utm_source=rss&utm_medium=rss&utm_campaign=arretes-et-deposes-en-prison-que-deviennent-ils-le-temps-de-la-justice",
        "clean_url": "matinlibre.com",
        "excerpt": "A l'instar du dossier Carlos Adohouannon, ex régisseur des impôts (Ministère de l'économie et des finances) accusé de détournement de plusieurs milliards FCfa, qui avait pris la clé des champs le 20 septembre 2019 et extradé du Sénégal vers le Bénin,",
        "summary": "A l'instar du dossier Carlos Adohouannon, ex régisseur des impôts (Ministère de l'économie et des finances) accusé de détournement de plusieurs milliards FCfa, qui avait pris la clé des champs le 20 septembre 2019 et extradé du Sénégal vers le Bénin, jeudi 17 septembre 2020, plusieurs autres cas sont dans les mains la justice, principalement […]",
        "rights": "matinlibre.com",
        "rank": 869184,
        "topic": "news",
        "country": "BJ",
        "language": "fr",
        "authors": "Matin Libre",
        "media": "https://matinlibre.com/wp-content/uploads/2023/07/1-2.jpg",
        "is_opinion": false,
        "twitter_account": null,
        "_score": 15.968863,
        "_id": "217d7d02fa158760f25f9de985e37df6"
      },
      {
        "title": "2026 au Bénin: Romuald Wadagni réagit à l'utilisation de son nom à 3 ans de la présidentielle",
        "author": "",
        "published_date": "2023-07-04 08:45:00",
        "published_date_precision": "timezone unknown",
        "link": "https://lanouvelletribune.info/2023/07/presidentielle-2026-au-benin-romuald-wadagni-met-fin-aux-speculations",
        "clean_url": "lanouvelletribune.info",
        "excerpt": "Romuald Wadagni, le ministre de l'Économie et des Finances du Bénin, a récemment pris la parole sur les réseaux sociaux pour réagir aux utilisations abusives de",
        "summary": "Romuald Wadagni, le ministre de l'Économie et des Finances du Bénin, a récemment pris la parole sur les réseaux sociaux pour réagir aux utilisations abusives de son patronyme et de ses photos en lien avec les prochaines élections présidentielles qui auront lieu dans notre pays en 2026. Dans une déclaration sur les réseaux sociaux ce matin, le ministre Wadagni a exprimé son dévouement exclusif envers la mission qui lui a été confiée par le chef de l'Etat béninois, Son Excellence le Président de la République Patrice Talon.",
        "rights": "lanouvelletribune.info",
        "rank": 124345,
        "topic": "politics",
        "country": "BJ",
        "language": "fr",
        "authors": "",
        "media": "https://lanouvelletribune.info/wp-content/uploads/2023/03/wadagni-6.webp",
        "is_opinion": false,
        "twitter_account": "@lntribune",
        "_score": 15.466936,
        "_id": "e0c428b070a9a12c421b061dc46e35e5"
      },

      
 
      {
        "title": "Le Bénin obtient environ 164 millions d'euros pour lutter contre les effets des changements climatiques",
        "author": "Croissance Afrique",
        "published_date": "2023-07-06 08:54:52",
        "published_date_precision": "full",
        "link": "https://api.follow.it/track-rss-story-click/v3/U7Xd8EWHO-aDrS6D8KWTdXMq2h3ehXEp",
        "clean_url": "follow.it",
        "excerpt": "(CROISSANCE AFRIQUE)-La Banque africaine de développement accorde 164,25 d'euros de prêts au Bénin, pour assainir le cadre de vie des populations et renforcer leur résilience face aux inondations q…",
        "summary": "(CROISSANCE AFRIQUE)-La Banque africaine de développement accorde 164,25 d'euros de prêts au Bénin, pour assainir le cadre de vie des populations et renforcer leur résilience face aux inondations qu'entraînent les changements climatiques.\n\n\nDestiné à mettre en œuvre le Programme d'assainissement pluvial des villes secondaires (PAPVS), ce financement a obtenu le feu vert du Conseil d'administration de la Banque, mercredi 5 juillet 2023 à Abidjan. Il se décline en deux prêts, l'un de 118,75 millions d'euros de la Banque africaine de développement et l'autre de 45,50 millions d'euros de l'Africa growing together fund , un fonds spécial cofinancé avec la Chine.",
        "rights": "follow.it",
        "rank": 2292,
        "topic": "news",
        "country": "IT",
        "language": "fr",
        "authors": "Croissance Afrique,En Ligne,Financières,Sarl,Stratégiques",
        "media": "https://i0.wp.com/croissanceafrique.com/wp-content/uploads/2022/09/Le-Benin-obtient-un-decaissement-de-150-millions-USD-de-la-Banque-mondiale-pour-booster-la-croissance.jpg?fit=1200%2C890&ssl=1",
        "is_opinion": false,
        "twitter_account": "@Croissanceafri1",
        "_score": 15.158317,
        "_id": "794b80ae9054153dd965044d1ad52cdc"
      },
      {
        "title": "Bénin : l'histoire du mythique orchestre \"Black Santiago\" racontée dans une série",
        "author": "TV5MONDE",
        "published_date": "2023-07-09 07:36:40",
        "published_date_precision": "full",
        "link": "https://information.tv5monde.com/afrique/video/benin-lhistoire-du-mythique-orchestre-black-santiago-racontee-dans-une-serie-2655273",
        "clean_url": "tv5monde.com",
        "excerpt": "Tiburce Bocovo, le co-réalisateur, et Chloé Lecerf, une des actrices, sont les invités de TV5Monde pour présenter leur nouvelle série, Black Santiago Club, un thriller musical qui raconte l'histoire d'un club de jazz mythique au Bénin.",
        "summary": "Bénin : l'histoire du mythique orchestre \"Black Santiago\" racontée dans une série\n\nTiburce Bocovo, le co-réalisateur, et Chloé Lecerf, une des actrices, sont les invités de TV5Monde pour présenter leur nouvelle série, Black Santiago Club, un thriller musical qui raconte l'histoire d'un club de jazz mythique au Bénin.",
        "rights": "tv5monde.com",
        "rank": 5811,
        "topic": "news",
        "country": "FR",
        "language": "fr",
        "authors": "TV5MONDE",
        "media": "https://information.tv5monde.com/sites/tv5-info/files/styles/seo_1200/public/tv5_jwplayer_field/Capture%20d%E2%80%99%C3%A9cran%202023-07-09%20%C3%A0%2009.27.29.png?itok=teOEg-Lw",
        "is_opinion": false,
        "twitter_account": "@tv5mondeinfo",
        "_score": 11.23786,
        "_id": "bab14bc5eeaf07c034a37fd5d64c33c6"
      },
      {
        "title": "Politique: Moele-Bénin bientôt en congrès ordinaire",
        "author": "Cochimau S. Houngbadji",
        "published_date": "2023-07-05 07:24:51",
        "published_date_precision": "full",
        "link": "https://beninwebtv.com/politique-moele-benin-bientot-en-congres-ordinaire",
        "clean_url": "beninwebtv.com",
        "excerpt": "Le Mouvement des élites engagées pour l'émancipation du Bénin (Moele-Bénin) s'active pour tenir son congrès ordinaire. De sources concordantes, ledit",
        "summary": "Le Mouvement des élites engagées pour l'émancipation du Bénin (Moele-Bénin) s'active pour tenir son congrès ordinaire. De sources concordantes, ledit congrès est prévue dans le mois de septembre. En septembre prochain, Moele-Bénin tiendra un congrès ordinaire qui réunira ses militants et instances dirigeantes. Une équipe est déjà mise sur place pour travailler sur l'organisation pratique […]\n\n\nL'article \nPolitique: Moele-Bénin bientôt en congrès ordinaire\n a été premièrement publié sur \nBenin Web TV\n.",
        "rights": "beninwebtv.com",
        "rank": 277525,
        "topic": "news",
        "country": "BJ",
        "language": "fr",
        "authors": "Cochimau S. Houngbadji",
        "media": "https://beninwebtv.com/wp-content/uploads/2021/07/maxresdefault-22.jpg",
        "is_opinion": false,
        "twitter_account": "@beninwebtv",
        "_score": 10.982987,
        "_id": "d1f2c4edcebbe19e82c8e4202c307a1d"
      },
      {
        "title": "Don de sang à la Fondation Moov Africa Bénin pour sauver des vies",
        "author": "Claudia Dianou",
        "published_date": "2023-07-07 17:23:10",
        "published_date_precision": "full",
        "link": "https://beninwebtv.com/don-de-sang-a-la-fondation-moov-africa-benin-pour-sauver-des-vies/",
        "clean_url": "beninwebtv.com",
        "excerpt": "La Fondation Moov Africa Bénin, dans la poursuite de son engagement social a organisé ce vendredi 7 juillet 2023, une journée de don de sang à la",
        "summary": "La Fondation Moov Africa Bénin, dans la poursuite de son engagement social a organisé ce vendredi 7 juillet 2023, une journée de don de sang à la Direction Générale de Moov Africa Bénin à Cotonou.\n \nDans le cadre de la célébration de ses 10 ans d'existence, la Fondation Moov Africa Bénin a organisé ce vendredi 7 juillet 2023, une journée de collecte de poches de sang à la Direction Générale de Moov Africa Bénin, en partenariat avec la Fondation Claudine Talon et l'Agence National pour la Transfusion Sanguine (ANTS).",
        "rights": "beninwebtv.com",
        "rank": 277525,
        "topic": "news",
        "country": "BJ",
        "language": "fr",
        "authors": "Claudia DIANOU",
        "media": "https://beninwebtv.com/wp-content/uploads/2023/07/image-46.png",
        "is_opinion": false,
        "twitter_account": "@beninwebtv",
        "_score": 1,
        "_id": "797018179c57b994d0af63dd476327d3"
      },
      {
        "title": "Les nouveaux projets de l'association lorientaise Toko-Bio pour soutenir un village du Bénin",
        "author": "",
        "published_date": "2023-07-06 17:19:58",
        "published_date_precision": "full",
        "link": "https://www.letelegramme.fr/morbihan/lorient-56100/les-nouveaux-projets-de-lassociation-lorientaise-toko-bio-pour-soutenir-un-village-du-benin-6388966.php",
        "clean_url": "letelegramme.fr",
        "excerpt": "L'association lorientaise Toko-Bio a présenté ces projets à venir, en assemblée générale, lundi 3 juillet.",
        "summary": "L'association lorientaise Toko-Bio a présenté ces projets à venir, en assemblée générale, lundi 3 juillet.\n \n \n \n \nLes membres de l'association Toko-Bio se sont réunis en assemblée générale, lundi 3 juillet. (Photo : Toka Bio)\n \n \n \n \n \n \n \n \nNée en 2020, Toko-Bio est une association destinée à promouvoir l'autosuffisance alimentaire d'un petit village du Bénin. Lundi 3 juillet, en assemblée générale, l'association lorientaise a fait le bilan de ses activités de la saison passée : forage d'un puits, électricité solaire, éducation à la terre, élevages, plantations, etc.",
        "rights": "letelegramme.fr",
        "rank": 9889,
        "topic": "news",
        "country": "FR",
        "language": "fr",
        "authors": "",
        "media": "https://media.letelegramme.fr/api/v1/images/view/64a6f7be1dd4324d0e620726/web_golden_xxl/64a6f7be1dd4324d0e620726.1",
        "is_opinion": false,
        "twitter_account": "@LeTelegramme",
        "_score": 10.694115,
        "_id": "312d38af856d578b6bb1f3d3052303b9"
      },
      {
        "title": "Bénin: les grandes décisions du Conseil des ministres du 05 juillet 2023",
        "author": "Cochimau S. Houngbadji",
        "published_date": "2023-07-05 11:19:35",
        "published_date_precision": "full",
        "link": "https://beninwebtv.com/benin-les-grandes-decisions-du-conseil-des-ministres-du-05-juillet-2023/",
        "clean_url": "beninwebtv.com",
        "excerpt": "Le gouvernement a tenu ce mercredi 05 juillet 2023 sa séance hebdomadaire de Conseil des ministres. Retrouvez ci-dessous les grandes décisions du",
        "summary": "Le gouvernement a tenu ce mercredi 05 juillet 2023 sa séance hebdomadaire de Conseil des ministres. Retrouvez ci-dessous les grandes décisions du conclave.\n \nMESURES NORMATIVES\n \n\n\nTransmission à l'Assemblée nationale, pour examen et vote, du projet de loi sur l'urbanisme en République du Bénin ;\n \nDécrets d'application de la loi n° 2018-10 du 02 juillet 2018 portant protection, aménagement et mise en valeur de la zone littorale en République du Bénin ;\n \nDécret fixant les modalités d'application des dispositions de la loi n° 2020-03 du 20 mars 2020 portant promotion et développement des micro, petites et moyennes entreprises en République du Bénin■ MESURES INDIVIDUELLESNominations : au ministère de la Justice et de la Législation et au ministère de la santé.",
        "rights": "beninwebtv.com",
        "rank": 277525,
        "topic": "politics",
        "country": "BJ",
        "language": "fr",
        "authors": "Cochimau S. Houngbadji",
        "media": "https://beninwebtv.com/wp-content/uploads/2022/05/Conseil-des-ministres.jpg",
        "is_opinion": false,
        "twitter_account": "@https://twitter.com/CochimauH?t=Fni90aydG2PxwDMy767EsA&s=09",
        "_score": 3,
        "_id": "f45c6834815a02fa667397aebd54c6f0"
      },
      {
        "title": "Bénin : La France livre trois hélicoptères Puma à l'armée",
        "author": "KOACI",
        "published_date": "2023-07-06 15:45:00",
        "published_date_precision": "timezone unknown",
        "link": "https://www.koaci.com/article/2023/07/06/benin/politique/benin-la-france-livre-trois-helicopteres-puma-a-larmee_170631.html",
        "clean_url": "koaci.com",
        "excerpt": "HélicoptèresEn proie à des attaques terroristes, le Bénin a décidé de renforcer son arsenal militaire.Pour venir à bout... - KOACI l'Info au Coeur de l'Afrique",
        "summary": "Pour venir à bout du terrorisme, le Bénin en partenariat avec la France a reçu de nouveaux équipements militaires pour renforcer le plan de riposte contre le terrorisme et les groupes armés.\n\nEn proie à des attaques terroristes, le Bénin a décidé de renforcer son arsenal militaire.\n\nAinsi, la France a livré trois hélicoptères Puma, destinés au transport de troupes.\n\nCes hélicoptères sont également armés. Livrés à Cotonou, les appareils auraient déjà été acheminés vers le nord du pays et effectué leur premier vol.",
        "rights": "koaci.com",
        "rank": 131902,
        "topic": "politics",
        "country": "FR",
        "language": "fr",
        "authors": "KOACI",
        "media": "https://www.koaci.com/assets/news/thumbnails/600/2023/07/photo_1688650681.jpg",
        "is_opinion": false,
        "twitter_account": null,
        "_score": 10.664467,
        "_id": "c3b416acd02d745b070a5c97b0aca05c"
      },
      {
        "title": "Prise en charge adéquate des grands brûlés : Les médecins anesthésistes réanimateurs du Bénin aguerris",
        "author": "",
        "published_date": "2023-07-09 15:45:00",
        "published_date_precision": "timezone unknown",
        "link": "https://www.gouv.bj/article/2294/prise-charge-adequate-grands-brules-medecins-anesthesistes-reanimateurs-benin-aguerris",
        "clean_url": "gouv.bj",
        "excerpt": null,
        "summary": "La Société des Médecins Anesthésistes Réanimateurs du Bénin (SMARB) a tenu sa journée monothématique sur la gestion des grands brûlés au Bénin. La cérémonie officielle d'ouverture des travaux a été présidée par le Ministre de la santé, Professeur Benjamin HOUNKPATIN. C'était le samedi 8 juillet 2023 au grand amphithéâtre Édouard GOUDOTÉ de la Faculté des Sciences de la Santé de Cotonou.\n\n\n\nLimiter les dégâts liés au spectre du feu en apportant les soins d'urgence appropriés pour une prise en charge adéquate des brûlures.",
        "rights": "gouv.bj",
        "rank": 89217,
        "topic": "news",
        "country": "BJ",
        "language": "fr",
        "authors": "",
        "media": "https://www.gouv.bj/upload/thumbnails/banners//908460075307001688913253.jpg?v=001",
        "is_opinion": false,
        "twitter_account": null,
        "_score": 10.516226,
        "_id": "7e2db0021bc90a193af3b563ae9c6ad7"
      },
      {
        "title": "Lutte contre le terrorisme : le Bénin se dote de 3 hélicoptères de combat",
        "author": "",
        "published_date": "2023-07-06 12:36:02",
        "published_date_precision": "full",
        "link": "https://lanouvelletribune.info/2023/07/lutte-contre-le-terrorisme-le-benin-se-dote-de-3-helicopteres-de-combat/",
        "clean_url": "lanouvelletribune.info",
        "excerpt": "Le Bénin a subi des attaques terroristes au cours de l'année 2021 où des militaires béninois ont tués. Lors de son discours sur l'Etat de la Nation devant les",
        "summary": "Le Bénin a subi des attaques terroristes au cours de l'année 2021 où des militaires béninois ont tués. Lors de son discours sur l'Etat de la Nation devant les députés le \nmercredi 29 décembre 202\n1 au Palais des Gouverneurs de\n Porto-Novo,\n le Président de la République du Bénin, \nPatrice Talon\n déclarait : \n«\n Nous\n avons été à plusieurs reprises éprouvés ces derniers temps…. Le Gouvernement prend déjà des mesures fortes et poursuivra les investissements nécessaires pour notre dispositif soit renforcé en moyens tant humains, logistiques que technologiques, afin que ce genre d'incursion sur notre territoire ne puisse continuer\n ».",
        "rights": "lanouvelletribune.info",
        "rank": 124345,
        "topic": "politics",
        "country": "BJ",
        "language": "fr",
        "authors": "",
        "media": "https://lanouvelletribune.info/wp-content/uploads/2023/01/51887909108_62d877c59a_k.jpg",
        "is_opinion": false,
        "twitter_account": "@lntribune",
        "_score": 10.492268,
        "_id": "c321b812c3137276f35467bed1fc9f11"
      },
      {
        "title": "COMMUNIQUE DE PRESSE",
        "author": "Matin Libre",
        "published_date": "2023-07-06 04:21:42",
        "published_date_precision": "full",
        "link": "https://matinlibre.com/2023/07/06/communique-de-presse-38/",
        "clean_url": "matinlibre.com",
        "excerpt": "Nestor Coffi, nouveau Représentant Résident de la Banque mondiale pour le BéninAssurer la mise en œuvre efficace et souple du Cadre de partenariat entre la Banque mondiale et le Bénin afin d'obtenir…",
        "summary": "Get real time updates directly on you device, subscribe now.\n \n\n\n \nNestor Coffi, nouveau Représentant Résident de la Banque mondiale pour le Bénin\n\n\nAssurer la mise en œuvre efficace et souple du Cadre de partenariat entre la Banque mondiale et le Bénin afin d'obtenir des résultats qui impactent la qualité de vie des populations.\n \nCotonou, le 5 juillet 2023. Le nouveau Représentant Résident de la Banque mondiale pour le Bénin a pris fonction officiellement le 1er juillet 2023. Monsieur Nestor Coffi, remplace Monsieur Atou Seck dont le mandat a pris fin le 30 juin 2023.",
        "rights": "matinlibre.com",
        "rank": 869184,
        "topic": "news",
        "country": "BJ",
        "language": "fr",
        "authors": "Matin Libre",
        "media": "https://matinlibre.com/wp-content/uploads/2023/07/9-2.jpg",
        "is_opinion": false,
        "twitter_account": null,
        "_score": 10.472714,
        "_id": "95619c56e230bfe72c7b5c6cda6d6dcf"
      },
      {
        "title": "Coris Bank International Bénin célèbre son 30 000ieme client",
        "author": "Marc Mensah",
        "published_date": "2023-07-06 11:45:00",
        "published_date_precision": "timezone unknown",
        "link": "http://www.24haubenin.info/?Coris-Bank-International-Benin-celebre-son-30-000ieme-client",
        "clean_url": "24haubenin.info",
        "excerpt": "30 000ieme client avoir fait confiance à Coris Bank International Bénin, M. Kodjodjou Olouranti Dieu-Donné a été récompensé. C'est à travers une cérémonie symbolique empreinte de solennité tenue,…",
        "summary": "30 000ieme client avoir fait confiance à Coris Bank International Bénin, M. Kodjodjou Olouranti Dieu-Donné a été récompensé. C'est à travers une cérémonie symbolique empreinte de solennité tenue, mercredi 05 juillet 2023, à l'Agence Abomey-Calavi de ‘' La Banque Autrement…''.\n\n\nCoris Bank International Bénin a témoigné sa gratitude à son 30 000ieme client pour la confiance placée en son institution. Monsieur Kodjodjou Olouranti Dieu-Donné, gérant d'établissement et 30 000ieme client, a reçu des mains du Directeur général adjoint de la Banque des cadeaux lors d'une cérémonie tenue, mercredi 05 juillet 2023, à l'Agence Abomey-Calavi.",
        "rights": "24haubenin.info",
        "rank": 853530,
        "topic": "news",
        "country": "BJ",
        "language": "fr",
        "authors": "Marc Mensah",
        "media": "http://www.24haubenin.info/local/cache-gd2/92/4fd36a4f8ec8e008696af42aa998ca.jpg?1688639286",
        "is_opinion": false,
        "twitter_account": "@24haubenin",
        "_score": 10.425727,
        "_id": "240a8c055cfbf75f2ad0611b9bcf81b8"
      },
      {
        "title": "Tournoi olympique féminin Paris 2024 : Les Amazones du Bénin affrontent la Guinée Bissau le 14 juillet",
        "author": "Peter Makelilo",
        "published_date": "2023-07-05 10:51:25",
        "published_date_precision": "full",
        "link": "https://lanouvelletribune.info/2023/07/tournoi-olympique-feminin-paris-2024-les-amazones-du-benin-affrontent-la-guinee-bissau-le-14-juillet/",
        "clean_url": "lanouvelletribune.info",
        "excerpt": "Dans le cadre du premier tour des éliminatoires du tournoi olympique féminin Paris 2024/zone Afrique, les Amazones olympiques du Bénin sont entrées en regroupe",
        "summary": "Dans le cadre du premier tour des éliminatoires du tournoi olympique féminin Paris 2024/zone Afrique, les Amazones olympiques du Bénin sont entrées en regroupement depuis ce mardi 04 juillet 2023. Pour ces éliminatoires, la sélection nationale féminine du Bénin croisera, le \n14 juillet 2023 au stade du 24 Septembre\n à Bissau, les crampons avec la Guinée Bissau et le \n18 juillet 2023\n pour le match retour, au stade de l'Amitié Général \n« Mathieu Kérékou »\n de \nKouhounou.\n \n \nContrairement aux hommes, chez les dames, les équipes engagées seront constituées des joueuses sans limite d'âge.",
        "rights": "lanouvelletribune.info",
        "rank": 124345,
        "topic": "news",
        "country": "BJ",
        "language": "fr",
        "authors": "Agbinkpan Ekotité,Peter Makelilo",
        "media": "https://lanouvelletribune.info/wp-content/uploads/2019/03/football-terrain.jpg",
        "is_opinion": false,
        "twitter_account": "@lntribune",
        "_score": 10.324191,
        "_id": "cf99b8023f462ddfc48640398edb18a3"
      },
      {
        "title": "Bénin: la CNSS échange avec l'ONPB sur la protection sociale dans les établissements pharmaceutiques",
        "author": "Romaric Déguénon",
        "published_date": "2023-07-05 06:56:35",
        "published_date_precision": "full",
        "link": "https://beninwebtv.com/benin-la-cnss-echange-avec-lonpb-sur-la-protection-sociale-dans-les-etablissements-pharmaceutiques/",
        "clean_url": "beninwebtv.com",
        "excerpt": "La Caisse Nationale de Sécurité Sociale (CNSS) a tenu ce mardi 4 juillet 2023 une séance d'échanges et de sensibilisation avec l'Ordre National des",
        "summary": "- Publicité-\n\n\n\n\n\n\nLa  Caisse Nationale de Sécurité Sociale (CNSS) a tenu ce mardi 4 juillet 2023 une séance d'échanges et de sensibilisation avec l'Ordre National des Pharmaciens du Bénin (ONPB) sur le thème : Protection Sociale dans les établissements pharmaceutiques. La salle de conférence de Bénin Royal Hôtel a servi de cadre à cette causerie-débat.\n \nProtection Sociale dans les établissements pharmaceutiques du Bénin. C'est au tour de ce thème qu'a échangé ce mardi au Bénin Royal Hôtel à Cotonou, la Caisse Nationale de Sécurité Sociale avec l'Ordre National des Pharmaciens du Bénin.",
        "rights": "beninwebtv.com",
        "rank": 277525,
        "topic": "news",
        "country": "BJ",
        "language": "fr",
        "authors": "Romaric Déguénon",
        "media": "https://beninwebtv.com/wp-content/uploads/2023/07/CNSS.jpg",
        "is_opinion": false,
        "twitter_account": "@beninwebtv",
        "_score": 10.3211565,
        "_id": "dc09ca2ae2be9f3e2a46cc33a6bc8205"
      },
      {
        "title": "Bénin: Lancement du projet PIRVaTEFoD",
        "author": "Matin Libre",
        "published_date": "2023-07-07 04:23:11",
        "published_date_precision": "full",
        "link": "https://matinlibre.com/2023/07/07/benin-lancement-du-projet-pirvatefod/",
        "clean_url": "matinlibre.com",
        "excerpt": "Au cours des dernières décennies, il est devenu impossible de parler de la sécurité alimentaire au Bénin sans poser la problématique de la question de la dégradation des terres, des forêts et des…",
        "summary": "Get real time updates directly on you device, subscribe now.\n \n\n\n \nAu cours des dernières décennies, il est devenu impossible de parler de la sécurité alimentaire au Bénin sans poser la problématique de la question de la dégradation des terres, des forêts et des habitats naturels dans un contexte de plus en plus marqué par les changements climatiques. C'est tout l'objet du projet Restauration et valorisation des terres dégradées et des écosystèmes forestiers pour une meilleure résilience climatique au Bénin (PIRVaTEFoD-Bénin).",
        "rights": "matinlibre.com",
        "rank": 869184,
        "topic": "news",
        "country": "BJ",
        "language": "fr",
        "authors": "Matin Libre",
        "media": "https://matinlibre.com/wp-content/uploads/2023/07/3-2.jpg",
        "is_opinion": false,
        "twitter_account": null,
        "_score": 10.314574,
        "_id": "5e65f6d18a76996ea256d8a0619e00ec"
      },
      {
        "title": "Préliminaires JO Paris 2024 : Les Étalons U23 dames corrigent les Amazones du Bénin (4-1) en amical",
        "author": "Abdoul Gani Barry",
        "published_date": "2023-07-09 20:15:53",
        "published_date_precision": "full",
        "link": "https://burkina24.com/2023/07/09/preliminaires-jo-paris-2024-les-etalons-u23-dames-corrigent-les-amazones-du-benin-4-1-en-amical",
        "clean_url": "burkina24.com",
        "excerpt": "L'information en temps réel, vidéos, reportages et analyses sur la politique, l'économie, culture et technologies au Burkina et dans le monde",
        "summary": "Préliminaires JO Paris 2024 : Les Étalons U23 dames corrigent les Amazones du Bénin (4-1) en amical\n\npublicite\n\n0 Partages Partager Twitter\n\nEn prélude au match aller comptant pour les préliminaires des Jeux Olympiques Paris 2024 contre le Mali, le Burkina Faso s'est offert ce dimanche 9 juillet, une victoire de choix face au Bénin (4-1) en match amical. La rencontre s'est disputée à huit clos au Stade Général Mathieu KEREKOU de Cotonou.\n\nLa suite après cette publicité\n\nC'est une équipe vivace et efficace selon le coach Pascal SAWADOGO qui est venue à bout des Amazones U23 du Bénin par le score de 4 buts à 1.",
        "rights": "burkina24.com",
        "rank": 253781,
        "topic": "news",
        "country": "CA",
        "language": "fr",
        "authors": "Abdoul Gani Barry",
        "media": "https://burkina24.com/wp-content/uploads/2023/07/IMG-20230708-WA0026.jpg.webp",
        "is_opinion": false,
        "twitter_account": "@burkina24",
        "_score": 10.285952,
        "_id": "3a055b939044fa1a94502d8f63644a46"
      },
      {
        "title": "Il servait de banque aux escrocs du Bénin",
        "author": "",
        "published_date": "2023-07-07 05:13:00",
        "published_date_precision": "timezone unknown",
        "link": "https://www.laliberte.ch/news/regions/il-servait-de-banque-aux-escrocs-du-benin-695252",
        "clean_url": "laliberte.ch",
        "excerpt": "Justice » Un Portugais de 35 ans, établi en Gruyère, avait ouvert quatre comptes bancaires pour le...",
        "summary": "Publié le 07.07.2023\n \nTemps de lecture estimé : \n 2 minutes \n \nJustice » Un Portugais de 35 ans, établi en Gruyère, avait ouvert quatre comptes bancaires pour le compte d'une bande d'escrocs du Bénin, qui y faisaient transiter le fruit de leurs arnaques.\n \nEn quinze mois, dix-huit victimes de la bande y ont versé quelque 24 000 francs, immédiatement et directement prélevés au Bénin.\n \nLeur banquier bénévole, qui a plaidé une naïveté et une patience difficilement concevables, a été condamné pour blanchiment à six mois de jours-amende, avec un sursis de quatre ans (qui représentent une menace de 18 000 francs sur son patrimoine), une amende ferme de 2500 francs et environ 2800 francs de frais de justice.",
        "rights": "laliberte.ch",
        "rank": 86025,
        "topic": "news",
        "country": "CH",
        "language": "fr",
        "authors": "",
        "media": "https://www.laliberte.ch/media/laliberte/image/0/thumb-default.jpg",
        "is_opinion": false,
        "twitter_account": null,
        "_score": 10.229532,
        "_id": "0c9d8ba9489fec77c0a18121710890b5"
      },
      {
        "title": "Bénin: Lutte contre les inondations et changements climatiques- La Bad apporte 164 millions d'euros",
        "author": "Par Bamba Moussa",
        "published_date": "2023-07-07 21:14:55",
        "published_date_precision": "full",
        "link": "https://fr.allafrica.com/stories/202307070862.html",
        "clean_url": "allafrica.com",
        "excerpt": "La Banque africaine de développement accorde 164,25 d'euros de prêts au Bénin, pour assainir le cadre de vie des populations et renforcer leur résilience face aux inondations qu'entraînent les…",
        "summary": "La Banque africaine de développement accorde 164,25 d'euros de prêts au Bénin, pour assainir le cadre de vie des populations et renforcer leur résilience face aux inondations qu'entraînent les changements climatiques.\nSelon l'Agence Ecofin, cette somme est destinée à mettre en œuvre le Programme d'assainissement pluvial des villes secondaires (Papvs).  Ce financement a obtenu le feu vert du Conseil d'administration de la Banque, mercredi 5 juillet 2023 à Abidjan. Il se décline en deux prêts, l'un de 118,75 millions d'euros de la Banque africaine de développement et l'autre de 45,50 millions d'euros de l'Africa growing together fund, un fonds spécial cofinancé avec la Chine.",
        "rights": "allafrica.com",
        "rank": 2320,
        "topic": "news",
        "country": "ZA",
        "language": "fr",
        "authors": "Par Bamba Moussa",
        "media": "https://cdn08.allafrica.com/static/images/structure/aa-logo-rgba-no-text-square.png",
        "is_opinion": false,
        "twitter_account": "@allafricafrench",
        "_score": 10.206498,
        "_id": "85012aee531df42b1d482365baaceb5a"
      },
      {
        "title": "Formations professionnelles duales soutenues par le projet ProFoP : Les centres de formation reçoivent des matériels et équipements",
        "author": "",
        "published_date": "2023-07-04 11:45:00",
        "published_date_precision": "timezone unknown",
        "link": "https://www.gouv.bj/article/2291/formations-professionnelles-duales-soutenues-projet-profop-centres-formation-recoivent-materiels-equipements/",
        "clean_url": "gouv.bj",
        "excerpt": "Aujourd'hui à 10:41|Comptes rendus|ÉducationDans le cadre du démarrage des formations professionnelles duales soutenues par le projet de Promotion de la Formation Professionnelle (ProFoP) au Bénin, le…",
        "summary": "Aujourd'hui à 10:41\n|\nComptes rendus\n|\nÉducation\nDans le cadre du démarrage des formations professionnelles duales soutenues par le projet de Promotion de la Formation Professionnelle (ProFoP) au Bénin, le Ministre des Enseignements Secondaire, Technique et de la Formation Professionnelle, Monsieur Kouaro Yves CHABI, a présidé le vendredi 30 juin 2023, la cérémonie de remise de matériels et équipements aux centres de formation. C'est le Lycée Technique Agricole Mèdji de Sékou qui a accueilli l'évènement en présence de l'Ambassadeur de l'Allemagne près le Bénin, Monsieur Michael DERUS.",
        "rights": "gouv.bj",
        "rank": 89217,
        "topic": "news",
        "country": "BJ",
        "language": "fr",
        "authors": "",
        "media": "https://www.gouv.bj/upload/thumbnails/banners//461570543984001688467395.jpg?v=001",
        "is_opinion": false,
        "twitter_account": null,
        "_score": 10.170625,
        "_id": "9c1b78a0a9cac6230b7852e36baf9096"
      },
      {
        "title": "5ème session de la Commission mixte sino-béninoise à Beijing : La Chine et le Bénin pour une relation plus consolidée et durable",
        "author": "",
        "published_date": "2023-07-06 11:45:00",
        "published_date_precision": "timezone unknown",
        "link": "https://www.gouv.bj/article/2293/5eme-session-commission-mixte-sino-beninoise-beijing-chine-benin-relation-plus-consolidee-durable/",
        "clean_url": "gouv.bj",
        "excerpt": "Aujourd'hui à 10:57|Comptes rendus|FinanceLe lundi 03 juillet 2023, s'est tenue, à Beijing, en marge de la 3ème édition de l'Exposition économique et commerciale de Changsha, la 5ème session de la…",
        "summary": "Aujourd'hui à 10:57\n|\nComptes rendus\n|\nFinance\nLe lundi 03 juillet 2023, s'est tenue, à Beijing, en marge de la 3ème édition de l'Exposition économique et commerciale de Changsha, la 5ème session de la Commission Mixte de Coopération sino-béninoise. La délégation béninoise aux travaux de ladite Commission a été conduite par le Ministre d'État, Ministre de l'Économie et des Finances en charge de la Coopération, Monsieur Romuald WADAGNI, et comprend entre autres, le Ministre des Affaires étrangères, Monsieur Olushégun ADJADI BAKARI, et le Ministre de l'Industrie et du Commerce, Madame Shadiya ASSOUMAN, ainsi que l'Ambassadeur du Bénin à Beijing, Monsieur Simon-Pierre ADOVELANDE.",
        "rights": "gouv.bj",
        "rank": 89217,
        "topic": "news",
        "country": "BJ",
        "language": "fr",
        "authors": "",
        "media": "https://www.gouv.bj/upload/thumbnails/banners//876920953785001688641263.jpg?v=001",
        "is_opinion": false,
        "twitter_account": null,
        "_score": 10.108271,
        "_id": "cf0ac4d3f590179f0ba2b3429693d228"
      },
      {
        "title": "Bénin : 164 millions d'euros de la BAD pour lutter contre les inondations urbaines dues aux changements climatiques",
        "author": "",
        "published_date": "2023-07-06 04:28:39",
        "published_date_precision": "full",
        "link": "https://www.agenceecofin.com/investissements-publics/0607-110005-benin-164-millions-d-euros-de-la-bad-pour-lutter-contre-les-inondations-urbaines-dues-aux-changements-climatiques",
        "clean_url": "agenceecofin.com",
        "excerpt": "La Banque africaine de développement accorde 164,25 d'euros de prêts au Bénin, pour assainir le cadre de vie des populations et renforcer leur résilience face aux inondations qu'entraînent les changements climatiques. Destiné à mettre en œuvre le Programme d'assainissement pluvial des villes secondaires (PAPVS), ce financement a obtenu le feu...",
        "summary": "La Banque africaine de développement accorde 164,25 d'euros de prêts au Bénin, pour assainir le cadre de vie des populations et renforcer leur résilience face aux inondations qu'entraînent les changements climatiques.\n\n\nDestiné à mettre en œuvre le Programme d'assainissement pluvial des villes secondaires (PAPVS), ce financement a obtenu le feu vert du Conseil d'administration de la Banque, mercredi 5 juillet 2023 à Abidjan. Il se décline en deux prêts, l'un de ...",
        "rights": "agenceecofin.com",
        "rank": 45316,
        "topic": "news",
        "country": "FR",
        "language": "fr",
        "authors": "",
        "media": "https://www.agenceecofin.com/media/k2/items/cache/a469ffb56829d78e87e4e977d67b0056_M.jpg",
        "is_opinion": false,
        "twitter_account": null,
        "_score": 10.048499,
        "_id": "3fd4012827e4aeb3bf16ee2c386bb134"
      },
      {
        "title": "Bénin : plus de 164 millions d'euros de la Banque africaine de développement pour lutter contre les inondations urbaines dues aux changements climatiques",
        "author": "African Development Bank Group",
        "published_date": "2023-07-05 18:28:06",
        "published_date_precision": "full",
        "link": "https://www.afdb.org/fr/news-and-events/press-releases/benin-plus-de-164-millions-deuros-de-la-banque-africaine-de-developpement-pour-lutter-contre-les-inondations-urbaines-dues-aux-changements-climatiques-62699",
        "clean_url": "afdb.org",
        "excerpt": "Le financement de la Banque va permettre aux autorités béninoises d'améliorer le système de drainage pluvial à Porto-Novo, Ouidah, Bohicon et Abomey.",
        "summary": "Le financement de la Banque va permettre aux autorités béninoises d'améliorer le système de drainage pluvial à Porto-Novo, Ouidah, Bohicon et Abomey.\n \nLa Banque africaine de développement accorde 164,25 d'euros de prêts au Bénin, pour assainir le cadre de vie des populations et renforcer leur résilience face aux inondations qu'entraînent les changements climatiques.\n\n\nDestiné à mettre en œuvre le Programme d'assainissement pluvial des villes secondaires (PAPVS), ce financement a obtenu le feu vert du Conseil d'administration de la Banque, mercredi 5 juillet 2023 à Abidjan.",
        "rights": "afdb.org",
        "rank": 7119,
        "topic": "news",
        "country": "CI",
        "language": "fr",
        "authors": "African Development Bank Group",
        "media": "https://www.afdb.org/sites/default/files/a1-drainage-pluvial.jpg",
        "is_opinion": false,
        "twitter_account": "@AfDB_Group",
        "_score": 15.059143,
        "_id": "f282b225b24754331bab581a1b516782"
      },
      {
        "title": "Zambie : MySol Grid Zambia (ENGIE) construira 60 mini-réseaux électriques",
        "author": "Agence Ecofin",
        "published_date": "2023-07-05 10:16:30",
        "published_date_precision": "full",
        "link": "https://www.agenceecofin.com/off-grid/0507-109979-zambie-mysol-grid-zambia-engie-construira-60-mini-reseaux-electriques",
        "clean_url": "agenceecofin.com",
        "excerpt": "En Afrique, les mini réseaux solaires qui répondent facilement à des demandes énergétiques isolées, se présentent comme une solution pour électrifier",
        "summary": "(Agence Ecofin) - En Afrique, les mini réseaux solaires qui répondent facilement à des demandes énergétiques isolées, se présentent comme une solution pour électrifier les zones rurales coupées des réseaux électriques nationaux.\n \nFacility for Energy Inclusion (FEI) a signé le 29 juin des documents de financement pour fournir 7,5 millions de dollars de dette senior à MySol Grid Zambia, une entité du groupe ENGIE Energy Access.\n \nCette transaction assure le financement et la flexibilité nécessaires à la construction de 60 mini-réseaux en Zambie dans le cadre du programme Increased Access to Electricity and Renewable Energy Production (IAEREP) de l'Union européenne.",
        "rights": "agenceecofin.com",
        "rank": 45316,
        "topic": "news",
        "country": "FR",
        "language": "fr",
        "authors": "Agence Ecofin",
        "media": "https://www.agenceecofin.com/media/k2/items/cache/71c4324cb2f720c503250e9efd9ed32c_M.jpg",
        "is_opinion": false,
        "twitter_account": null,
        "_score": 14.518161,
        "_id": "d74dca668acd7efe26ce02d3d709bcec"
      },
      {
        "title": "Bénin: la CNSS échange avec l'ONPB sur la protection sociale dans les établissements pharmaceutiques",
        "author": "Romaric Déguénon",
        "published_date": "2023-07-05 06:56:35",
        "published_date_precision": "full",
        "link": "https://beninwebtv.com/benin-la-cnss-echange-avec-lonpb-sur-la-protection-sociale-dans-les-etablissements-pharmaceutiques/",
        "clean_url": "beninwebtv.com",
        "excerpt": "La Caisse Nationale de Sécurité Sociale (CNSS) a tenu ce mardi 4 juillet 2023 une séance d'échanges et de sensibilisation avec l'Ordre National des",
        "summary": "- Publicité-\n\n\n\n\n\n\nLa  Caisse Nationale de Sécurité Sociale (CNSS) a tenu ce mardi 4 juillet 2023 une séance d'échanges et de sensibilisation avec l'Ordre National des Pharmaciens du Bénin (ONPB) sur le thème : Protection Sociale dans les établissements pharmaceutiques. La salle de conférence de Bénin Royal Hôtel a servi de cadre à cette causerie-débat.\n \nProtection Sociale dans les établissements pharmaceutiques du Bénin. C'est au tour de ce thème qu'a échangé ce mardi au Bénin Royal Hôtel à Cotonou, la Caisse Nationale de Sécurité Sociale avec l'Ordre National des Pharmaciens du Bénin.",
        "rights": "beninwebtv.com",
        "rank": 277525,
        "topic": "news",
        "country": "BJ",
        "language": "fr",
        "authors": "Romaric Déguénon",
        "media": "https://beninwebtv.com/wp-content/uploads/2023/07/CNSS.jpg",
        "is_opinion": false,
        "twitter_account": "@beninwebtv",
        "_score": 14.423234,
        "_id": "dc09ca2ae2be9f3e2a46cc33a6bc8205"
      },

      {
        "title": "Plus 100 milliards FCFA pour Porto-Novo, Ouidah, Abomey et Bohicon",
        "author": "Ignace B. Fanou",
        "published_date": "2023-07-06 11:45:00",
        "published_date_precision": "timezone unknown",
        "link": "http://www.24haubenin.info/?Porto-Novo-Ouidah-Abomey-et-Bohicon-beneficient-de-164-25-millions-d-euros-de",
        "clean_url": "24haubenin.info",
        "excerpt": "Quatre communes du Bénin (Porto-Novo, Ouidah, Abomey et Bohicon) viennent de bénéficier de 164,25 millions d'euros de la Banque Africaine de Développement (BAD) soit plus de 100 milliards de FCFA pour…",
        "summary": "Quatre communes du Bénin (Porto-Novo, Ouidah, Abomey et Bohicon) viennent de bénéficier de 164,25 millions d'euros de la Banque Africaine de Développement (BAD) soit plus de 100 milliards de FCFA pour le financement de l'assainissement du cadre de vie de leurs populations et le renforcement de leur résilience face aux inondations. L'accord de financement a été autorisé, mercredi 05 juillet 2023, par le Conseil d'administration de la BAD.\n\n\nLe Conseil d'administration de la Banque Africaine de Développement (BAD) a donné son accord, mercredi 05 juillet 2023, pour l'octroi d'un financement de 164,25 millions d'euros au Bénin.",
        "rights": "24haubenin.info",
        "rank": 853530,
        "topic": "news",
        "country": "BJ",
        "language": "fr",
        "authors": "Ignace B. Fanou,Marc Mensah",
        "media": "http://www.24haubenin.info/local/cache-gd2/e6/0f9d8ab632e5fd54f8529121bfe9e4.png?1688639454",
        "is_opinion": false,
        "twitter_account": "@24haubenin",
        "_score": 12,
        "_id": "8824be98141f1a2c0e84e4d43ae88c87"
      },
      {
        "title": "Bénin : plus de 164 millions d'euros de la Banque africaine de développement pour lutter contre les inondations urbaines dues aux changements climatiques",
        "author": "Apo Group",
        "published_date": "2023-07-06 14:45:00",
        "published_date_precision": "timezone unknown",
        "link": "https://afdb.africa-newsroom.com/press/benin--plus-de-164-millions-deuros-de-la-banque-africaine-de-developpement-pour-lutter-contre-les-inondations-urbaines-dues-aux-changements-climatiques",
        "clean_url": "africa-newsroom.com",
        "excerpt": "Destiné à mettre en œuvre le Programme d'assainissement pluvial des villes secondaires (PAPVS), ce financement a obtenu le feu vert du Conseil d'administration de la Banque, mercredi 5 juillet 2023 à…",
        "summary": "ABIDJAN, Côte d'Ivoire, 6 juillet 2023/APO Group/ -- \n \nLa Banque africaine de développement (\nwww.AfDB.org\n) accorde 164,25 d'euros de prêts au Bénin, pour assainir le cadre de vie des populations et renforcer leur résilience face aux inondations qu'entraînent les changements climatiques.\n \nDestiné à mettre en œuvre le Programme d'assainissement pluvial des villes secondaires (PAPVS), ce financement a obtenu le feu vert du Conseil d'administration de la Banque, mercredi 5 juillet 2023 à Abidjan.",
        "rights": "africa-newsroom.com",
        "rank": 71737,
        "topic": "news",
        "country": "CH",
        "language": "fr",
        "authors": "Afdb,Africa Newsroom,African Development Bank Group,Apo Group",
        "media": "https://afdb.africa-newsroom.com/files/large/a43d857a52fe022",
        "is_opinion": false,
        "twitter_account": null,
        "_score": 13.8407135,
        "_id": "11f31e041a5d9045af3a2c216f52f616"
      },
      {
        "title": "Sommet de l'UEMOA à Bissau: vers une réintégration du Mali, une refonte des statuts à venir",
        "author": "Texte Par",
        "published_date": "2023-07-09 03:33:36",
        "published_date_precision": "full",
        "link": "https://www.rfi.fr/fr/afrique/20230709-sommet-de-l-uemoa-%C3%A0-bissau-vers-une-r%C3%A9int%C3%A9gration-du-mali-une-refonte-des-statuts-%C3%A0-venir",
        "clean_url": "rfi.fr",
        "excerpt": "Le sommet extraordinaire de l'Union économique et monétaire ouest-africaine (UEMOA) s'est achevé samedi à Bissau. Il a duré quelques heures. Le président béninois Patrice Talon, le Nigérien Mohamed Bazoum…",
        "summary": "Le sommet extraordinaire de l'Union économique et monétaire ouest-africaine (UEMOA) s'est achevé samedi à Bissau. Il a duré quelques heures. Le président béninois Patrice Talon, le Nigérien Mohamed Bazoum et Oumar Cissoko Emballo, de Guinée-Bissau, étaient présents. Les présidents sénégalais, ivoirien et togolais étaient représentés. Assimi Goïta était lui absent, le Mali étant suspendu des instances de l'UEMOA. En attendant le communiqué officiel, on apprend que cette suspension est levée.\n\nLe président nigérien Mohamed Bazoum s'est longuement exprimé durant le sommet de l'UEMOA à Bissau, le 8 juillet 2023.",
        "rights": "rfi.fr",
        "rank": 1509,
        "topic": "news",
        "country": "FR",
        "language": "fr",
        "authors": "Jean-Luc Aplogan,RFI,Texte Par",
        "media": "https://s.rfi.fr/media/display/faa76814-1e05-11ee-99e3-005056bfb2b6/w:1280/p:16x9/AP23173317610913.jpg",
        "is_opinion": false,
        "twitter_account": "@rfi",
        "_score": 13.382576,
        "_id": "3dd655b5f672545912893f542653874d"
      },
      {
        "title": "Investissements. Africa50 ambitionne une levée de fonds à 500 millions de dollars",
        "author": "abdellah",
        "published_date": "2023-07-04 11:15:39",
        "published_date_precision": "full",
        "link": "https://www.infomediaire.net/investissements-africa50-ambitionne-une-levee-de-fonds-a-500-millions-de-dollars",
        "clean_url": "infomediaire.net",
        "excerpt": "Le fonds de capital-investissement pour les infrastructures, qui devrait fermer dans les prochains mois, a jusqu'à présent reçu des promesses de dons de la Société financière internationale et de 18 investisseurs institutionnels sur le continent, indique Africa50.",
        "summary": "La plateforme d'investissements basée au Maroc, Africa50, vient d'annoncer son ambition de procéder à une levée de fonds de 500 millions de dollars. Ce montant servira au financement de différents projets, notamment dans les énergies, les transports, les télécoms et l'eau.\n\nAvec une expérience de plus de 10 ans, la plateforme a été lancée par la Banque Africaine pour le Développement (BAD) et différents gouvernements du continent. Sa mission est d'accompagner le développement de l'Afrique à travers différentes actions.",
        "rights": "infomediaire.net",
        "rank": 420286,
        "topic": "news",
        "country": "MA",
        "language": "fr",
        "authors": "abdellah",
        "media": "https://www.infomediaire.net/wp-content/uploads/2023/07/Africa50.jpg",
        "is_opinion": false,
        "twitter_account": null,
        "_score": 13.334833,
        "_id": "02a4b0851c24b7df4ef8657c3a62b3aa"
      },
      {
        "title": "Les grandes mutations économiques projetées au sein de l'UEMOA en 2023",
        "author": "",
        "published_date": "2023-07-10 15:15:00",
        "published_date_precision": "timezone unknown",
        "link": "https://afriquinfos.com/afrique-de-louest/les-grandes-mutations-economiques-projetees-au-sein-de-luemoa-en-2023/",
        "clean_url": "afriquinfos.com",
        "excerpt": "Bissau (© 2023 Afriquinfos)- Pour cette année 2023, l'Union Économique et Monétaire Ouest Africaine (UEMOA) projette une croissance de 7% contre 5,9% en 2022. Par ailleurs, l'inflation est en net…",
        "summary": "Bissau (© 2023 Afriquinfos)- Pour cette année 2023, l'Union Économique et Monétaire Ouest Africaine (UEMOA) projette une croissance de 7% contre 5,9% en 2022. Par ailleurs, l'inflation est en net retrait devant se stabiliser à 4,4% à la fin de l'année contre 7% une année plus tôt. C'est ce qu'indique un communiqué publié à l'issue de la session extraordinaire de la Conférence des chefs d'Etat et de gouvernement du bloc régional tenue samedi 8 juillet à Bissau.\n« \nAbordant l'évolution récente de la situation économique et financière de l'Union et les perspectives, la Conférence des chefs d'Etat et de gouvernement se félicite de la résilience des économies de la zone dont le taux de croissance économique est prévu à 7% en 2023, après 5,9% en 2022, malgré les chocs enregistrés sur le plan international et au sein de l'espace communautaire \n», souligne le communiqué.",
        "rights": "afriquinfos.com",
        "rank": 212316,
        "topic": "news",
        "country": "CI",
        "language": "fr",
        "authors": "",
        "media": "https://afriquinfos.com/wp-content/uploads/2023/07/Croissance-Uemoa-dr.jpg",
        "is_opinion": false,
        "twitter_account": "https://twitter.com/AfriquinfosLive",
        "_score": 13.226583,
        "_id": "76066ba6cae7111a64fe6b9a6d62a0a3"
      },
      {
        "title": "Ni oui, ni non ! Romuald Wadagni livre sa position sur la présidentielle 2026 au Bénin",
        "author": "Edouard Djogbénou",
        "published_date": "2023-07-04 09:22:24",
        "published_date_precision": "full",
        "link": "https://beninwebtv.com/ni-oui-ni-non-romuald-wadagni-livre-sa-position-sur-la-presidentielle-2026-au-benin/",
        "clean_url": "beninwebtv.com",
        "excerpt": "Romuald Wadagni a-t-il des ambitions pour 2026 ? Dans un message de mise au point publié ce mardi 04 juillet 2023, le Ministre d'Etat n'a rien exclu. Il a",
        "summary": "- Publicité-\n\n\n\n\n\n\nRomuald Wadagni a-t-il des ambitions pour 2026 ? Dans un message de mise au point publié ce mardi 04 juillet 2023, le Ministre d'Etat n'a rien exclu. Il a cependant montré une prudence sur le timing.\n \nNi oui ni non ! C'est la position qu'affiche actuellement Romuald Wadagni face une éventuelle candidature pour succéder à Patrice Talon. Le ministre d'Etat reste prudent et s'éloigne de toutes tractations de suscitation de candidature, mais rien ne prouve qu'il ne veut pas. Peut-être une stratégie politique pour ne pas être très vite ciblé par d'éventuel adversaire au sein de la mouvance présidentielle.",
        "rights": "beninwebtv.com",
        "rank": 277525,
        "topic": "news",
        "country": "BJ",
        "language": "fr",
        "authors": "Edouard Djogbénou",
        "media": "https://beninwebtv.com/wp-content/uploads/2021/05/wadagni.jpg",
        "is_opinion": false,
        "twitter_account": "@beninwebtv",
        "_score": 3,
        "_id": "6d7f7396a660b98d562d06365e73a8c2"
      },
      {
        "title": "Vision UEMOA 2040: L'Union interpelle sur la nécessité du reversement du \"Prélèvement communautaire de solidarité\"",
        "author": "",
        "published_date": "2023-07-10 15:15:00",
        "published_date_precision": "timezone unknown",
        "link": "https://afriquinfos.com/afrique-de-louest/20230710vision-uemoa-2040-la-commission-de-lunion-interpelle-sur-le-reversement-du-prelevement-communautaire-de-solidarite/",
        "clean_url": "afriquinfos.com",
        "excerpt": "Bissau (© 2023 Afriquinfos)- La Conférence des Chefs d'Etat et de Gouvernement de l'Union Économique et Monétaire Ouest Africaine (UEMOA), s'est appropriée l'état d'avancement du processus…",
        "summary": "Bissau (© 2023 Afriquinfos)- La Conférence des Chefs d'Etat et de Gouvernement de l'Union Économique et Monétaire Ouest Africaine (UEMOA), s'est appropriée l'état d'avancement du processus d'élaboration de la Vision prospective de l'UEMOA à l'horizon 2040. Et a rappelé la nécessité pour les Etats membres de veiller à un reversement régulier du Prélèvement Communautaire de Solidarité (PCS). C'était à la faveur d'une nouvelle grand-messe de l'Union à Bissau ce 8 juillet.\nCette mesure permettra de doter l'Union d'un outil d'anticipation dans le long terme en vue d'asseoir les bases de ses choix et priorités stratégiques dans le cadre de l'approfondissement de l'intégration régionale.",
        "rights": "afriquinfos.com",
        "rank": 212316,
        "topic": "news",
        "country": "CI",
        "language": "fr",
        "authors": "",
        "media": "https://afriquinfos.com/wp-content/uploads/2023/07/UEMOA-PCS-dr-1024x585.jpg",
        "is_opinion": false,
        "twitter_account": "https://twitter.com/AfriquinfosLive",
        "_score": 12.702306,
        "_id": "9fad1e702184789221fa7d519fa5609a"
      },
      {
        "title": "L'ACA change de nom pour devenir l'ATIDI, ouvre ses assemblées générales annuelles2023",
        "author": "Croissance Afrique",
        "published_date": "2023-07-07 07:49:27",
        "published_date_precision": "full",
        "link": "https://api.follow.it/track-rss-story-click/v3/U7Xd8EWHO-aPW0WMEzBiuIfjc6hd5eWF",
        "clean_url": "follow.it",
        "excerpt": "Kigali, Rwanda, le 6 juillet 2023 – Le Premier ministre rwandais a ouvert aujourd'hui l'Assemblée générale annuelle (AGA) 2023 de l'Agence pour l'Assurance pour le développe…",
        "summary": "Kigali, Rwanda, le 6 juillet 2023 –\n \nLe Premier ministre rwandais a ouvert aujourd'hui l'Assemblée générale annuelle (AGA) 2023 de l'Agence pour l'Assurance pour le développement du commerce et de l'investissement en Afrique (ATIDI). L'AGA, qui réunit les représentants des 21 États membres de l'organisation multilatérale et quelques représentants d'actionnaires institutionnels, validera ses résultats après un exercice 2022 difficile, marqué par de fortes turbulences liées aux crises multiples (sanitaire, politique, économique et climatique) qui ont secoué le monde.",
        "rights": "follow.it",
        "rank": 2292,
        "topic": "news",
        "country": "IT",
        "language": "fr",
        "authors": "Croissance Afrique,En Ligne,Financières,Sarl,Stratégiques",
        "media": "https://i0.wp.com/croissanceafrique.com/wp-content/uploads/2023/07/358123902_846084603756715_4115120261637494315_n.jpg?fit=1200%2C800&ssl=1",
        "is_opinion": false,
        "twitter_account": "@Croissanceafri1",
        "_score": 12.541131,
        "_id": "552faa991594be5588bfdb41011fba23"
      },
      {
        "title": "UEMOA: la croissance repart à la hausse, l'inflation baisse",
        "author": "Rédaction",
        "published_date": "2023-07-09 17:33:47",
        "published_date_precision": "full",
        "link": "http://www.financialafrik.com/2023/07/09/uemoa-la-croissance-repart-a-la-hausse-linflation-baisse",
        "clean_url": "financialafrik.com",
        "excerpt": "Fin de la levée de la suspension du Mali dans les organes de l'institution \n\n\n\nL'Union Économique et Monétaire Ouest Africaine (UEMOA) projette une",
        "summary": "Fin de la levée de la suspension du Mali dans les organes de l'institution\n\nL'Union Économique et Monétaire Ouest Africaine (UEMOA) projette une croissance de 7% en 2023 contre 5,9% en 2022. Autre bonne nouvelle, l'inflation est en net retrait devant se stabiliser à 4,4% à la fin de l'année contre 7% une année plus tôt. Ce sont là les principales conclusions de la Conférence des Chefs d'Etat et de Gouvernement de l'UEMOA réunie le 8 juillet 2023 à Bissau sous la présidence du nigérien Mohamed Bazoum et en présence des présidents Patrice Talon du Bénin et Umaro Sissoco EMBALO de la Guinée Bissau, du vice-président de la Côte d'Ivoire, Tiémoko Meyliet KONE, du burkinabé Aboubakar NACANABO, Ministre de l'Economie, des Finances et de la Prospective, du sénégalais Mamadou Moustapha BA, Ministre des Finances et du Budget, du Professeur Robert DUSSEY, Ministre togolais des Affaires Etrangères, de l'Intégration Régionale et des Togolais de l'Extérieur.",
        "rights": "financialafrik.com",
        "rank": 149983,
        "topic": "news",
        "country": "FR",
        "language": "fr",
        "authors": "Rédaction",
        "media": "https://www.financialafrik.com/wp-content/uploads/2023/07/57067444-9D01-4197-BC33-08136A7C2AD9.jpeg",
        "is_opinion": false,
        "twitter_account": "@Financialafrik",
        "_score": 12.499587,
        "_id": "e9c168d3756f3cb60fe5db3e9d6b088d"
      }
    ])
  }),
  getters: {
    getArticles: (state) => state.articles
  }
})
